name: CI

on:
  pull_request:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  # Sparse cargo registry for faster updates
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      # Handle cargo check and cargo clippy warnings as errors
      RUSTFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy
      - name: Install alsa and udev
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
      - name: Run cargo clippy
        run: cargo clippy --workspace --all-features --tests --examples --exclude yarnspinner_without_bevy_examples
      - name: Run cargo clippy for serde
        run: cargo clippy --workspace --tests --features serde --exclude yarnspinner_without_bevy
_examples
      - name: Run cargo clippy for bevy
        run: cargo clippy --workspace --tests --features bevy
      - name: Run cargo clippy for non-bevy
        run: cargo clippy --tests
        working-directory: examples/yarnspinner_without_bevy


  format:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt
      - name: Run cargo fmt
        run: cargo fmt --check --all

  doc:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-D warnings"
      RUSTDOCFLAGS: '--deny warnings'
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Install alsa and udev
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
      - name: Run cargo doc
        run: cargo doc --no-deps --workspace --all-features

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Install alsa and udev
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
      - name: Run cargo test
        run: cargo test
        working-directory: crates/yarnspinner
      - name: Run cargo test
        run: cargo test
        working-directory: examples/yarnspinner_without_bevy
      - name: Run cargo test
        run: cargo test --workspace --all-features --exclude yarnspinner_without_bevy_examples
      - name: Run doc tests
        run: cargo test --workspace --doc
